### ISSUE TITLE
Sys_LoadLibrary error: steam_api.so

### ISSUE THREAD

**Issue by TheTrigger** [qdm12/cod4-docker#6]
```
...
Unable to resolve hostname cod4update.cod4x.me:80
...
Unable to resolve hostname raw.githubusercontent.com:443
Error: Sys_LoadLibrary error: steam_api.so: cannot open shared object file: No such file or directory
Error: steam_api.so not found or it was not possible to load. Error is: no error occurred while loading shared library. Steam is not going to work.
```
I tried to add static libraries but still same error

It works running only: `./cod4x18_dedrun +map_rotate` [from this](https://cod4x.me/index.php?/forums/topic/1227-steam-doesnt-start-in-cod4x-18/&do=findComment&comment=5971)

**Comment by qdm12** [comment]
Hi there!

It also gives me the steam error but the server works nonetheless for me. Why do you need steam functionality?

On a side note, I'm completely reworking the image now to have a better entrypoint, maybe run without os on scratch, have a bundled http server to serve mods & maps, and have a udp proxy as the container doesn't work on Windows for example and would need a proxy. So adding a fix for you would likely fit this weekend :wink:

**Comment by TheTrigger** [comment]
Yeah I don't need steam, the server seemed not to start but I could have been wrong then, honestly I don't remember I made dozens of different attempts in different ways.
However, I would like to tell you that a `guest` user already exists on Alpine, you could want to use it for the next release

Thanks for your work!! 😃

**Comment by TheTrigger** [comment]
I did another deploy, it works only as root, any suggestions?

**Comment by qdm12** [comment]
For example, I use the following docker-compose.yml:

```yml
version: '3'
services:
  cod4:
    image: qmcgaw/cod4
    container_name: cod4
    volumes:
      - ./cod4/main:/home/user/cod4/main
      - ./cod4/zone:/home/user/cod4/zone:ro
      - ./cod4/mods:/home/user/cod4/mods
      - ./cod4/usermaps:/home/user/cod4/usermaps:ro
      - ./cod4/logs:/home/user/.callofduty4
    network_mode: bridge
    ports:
      - 28960:28960/udp
    command: +set dedicated 2+set sv_cheats 1+set sv_maxclients 64+set fs_game mods/normal+exec server.cfg+map_rotate
    restart: always
```

Where I have a server.cfg file in `./cod4/mods/normal/server.cfg` and it works, without root.

Do you mind sharing your docker run command or docker-compose.yml? And maybe your full log to see what's wrong more precisely.

The newer Docker image version is still in the works, hopefully I'll finish it tomorrow/Tuesday.

Also nice I didn't know about the `guest` user on Alpine! Time for me to change many of my images 😆
