### ISSUE TITLE
Masterlist

### ISSUE THREAD

**Issue by Freekers** [qdm12/cod4-docker#8]
In order for the server to show up on the Activision Masterlist, you need to use `host` network mode for the container so that it can bind to the WAN/Internet IP address of your server. Additionally, you need to set `+set net_ip 123.123.123.123 +set net_port 28961` as `ARGS` environment variable.

If using `bridge` network mode, the container will bind to the IP address of the Docker network and therefore won't show up on the Activision Masterlist, as the heartbeat will send a ['local' IP-address](https://docs.docker.com/network/network-tutorial-standalone/) to the Masterserver (e.g. 172.16.X.X.).

Perhaps you can add this to the README :)

**Comment by qdm12** [comment]
Nice, many thanks! I'll definitely add it to the readme. Although it would be nice to somehow make it work in bridge mode, but it may be impossible.

**Comment by Freekers** [comment]
I'm not sure. I tried several approaches and this was the only one that worked for me in order to get the server to show up on the Activision Masterlist.

**Comment by TheTrigger** [comment]
I still can't register to cod4x master server 😢
Meanwhile, another (bad, with precompiled files) image I created works ..
Here my stack:
```yml
version: "3"
services:
  cod4-server:
    image: qmcgaw/cod4:latest
    container_name: cod4x-server-standard
    volumes:
      - /opt/cod4x/server/main:/home/user/cod4/main
      - /opt/cod4x/server/zone:/home/user/cod4/zone:ro
      - /opt/cod4x/server/mods:/home/user/cod4/mods
      - /opt/cod4x/server/usermaps:/home/user/cod4/usermaps:ro
      - /opt/cod4x/logs/standard:/home/user/.callofduty4
    network_mode: host
    stdin_open: true
    tty: true
    ports:
      - 28960:28960/udp
    command:
      [
        "+set dedicated 2",
        "+sv_authtoken mytoken",
        "+set sv_punkbuster 0",
        "+set rcon_password mypassword",
        "+set sv_maxclients 24",
        "+set ui_maxclients 32",
        "+set net_ip mypublicipv4",
        "+set net_port 28960",
        "+exec server.cfg",
        "+map_rotate",
      ]
    restart: unless-stopped
```

**Comment by Freekers** [comment]
Your docker-compose looks fine to me, but you can remove the following lines:
```
    stdin_open: true
    tty: true
    ports:
      - 28960:28960/udp
```
Ports are not used in network_mode host.

Looking at the date of the image on Docker Hub, I suspect the image of @qdm12 has to be rebuild because it doesn't have the sv_authtoken variable incorporated yet, which is now enforced to be listed on the cod4x.me master. Judging from the announcement post on the cod4x.me forums, they incorporated that into their code just áfter the last build of the @qdm12 Docker image.

Source: https://cod4x.me/index.php?/forums/topic/2814-new-requirement-for-cod4-x-servers-to-get-listed-on-masterserver/

**Comment by TheTrigger** [comment]
I use `-it` so I can attach to the process and launch commands

Correct me if I'm wrong but it should work with `$@` passing any parameter from `command`
<https://github.com/qdm12/cod4-docker/blob/60362e01b79ad15866f9aab2ebfa7b3752a7ac76/entrypoint.sh#L72>

**Comment by Freekers** [comment]
I'm not sure how that relates to what I said above.

The COD4x version in qdm12's Docker image needs to be updated in order to support the new token requirement by COD4x for their masterserver. This is done by updating the version number in the Dockerfile and rebuilding the image:
https://github.com/qdm12/cod4-docker/blob/60362e01b79ad15866f9aab2ebfa7b3752a7ac76/Dockerfile#L5

For example, try the fork of skrtheboss, which uses an update COD4x version: https://github.com/skrtheboss/cod4-docker

**Comment by TheTrigger** [comment]
Oh sorry now I got it, @qdm12 is working on the new Dockerfile

**Comment by qdm12** [comment]
Hello all, sorry for not answering earlier. So I just created [that issue](https://github.com/callofduty4x/CoD4x_Server/issues/299) in order to have releases, because the image is based on Alpine to keep a small size and so we need to build the binary from source.

I just made a `v17.7.2` release with its corresponding Docker tag `v17.7.2` (Alpine 3.11, cod4x v17.7.2 and shell entrypoint).

I will make another release using the latest commit available for now and name the Docker tag with the short commit. Both `:latest` and this docker tag will point to the latest source code from the cod4x repository.

I'm still working on making that fancy entrypoint (udp proxy + http static file server + launch cod4x, eventually restart it etc.), but it's not done unfortunately (all in 6MB extra). I will comment here once I've setup more releases/docker tags for you to try.

**Comment by qdm12** [comment]
`qmcgaw/cod4` and `qmcgaw/cod4:v17.8` now use the commit corresponding to the version change to v17.8 for cod4xServer. Note that you might have to update your cod4 client. I'll dig into the masterlist issue in the coming days, but feel free to try with the newer image 😉

**Comment by TheTrigger** [comment]
Nice! I will try soon!

Here my working sketch FTP server (I had 15kb/s problem with HTTP)

```yml
  ftpd_server: # https://github.com/stilliard/docker-pure-ftpd
    image: stilliard/pure-ftpd
    container_name: cod4-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # mount only mods and usermaps
      - /opt/cod4x/server/mods:/home/username/mods:ro
      - /opt/cod4x/server/usermaps:/home/username/usermaps:ro
      - /opt/cod4x/passwd:/etc/pure-ftpd/passwd
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_HOME: /home/username
      FTP_USER_NAME: cod4fdl
      FTP_USER_PASS: cod4fdl
```
